# Removing the obsolete version attribute

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ghostly_backend
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/app:/app/app # Mount app code for hot-reloading
    # Port 8000 is not exposed directly to host anymore, proxied via Nginx
    # ports:
    #   - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1 # Ensures Python logs appear without delay
    networks:
      - default
      - supabase_network

  # Original Vue/Vite Frontend Service (Restored)
  frontend:
    build:
      context: ./frontend # Original context
      dockerfile: Dockerfile
      target: build-stage # Original target
    container_name: ghostly_frontend # Original name
    # Use Vite dev server for development with hot-reload
    command: npm run dev -- --host 0.0.0.0 --port 5173 # Original command
    volumes:
      - ./frontend/src:/app/src # Original volumes
      - ./frontend/public:/app/public
      - /app/node_modules
    # Port 5173 is internal, proxied via Nginx
    # ports:
    #  - "5173:5173"
    depends_on:
      - backend # Original dependency
    env_file:
      - ./frontend/.env # Original env_file
    environment:
      - NODE_ENV=development
    networks:
      - default
      - supabase_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: ghostly_nginx
    ports:
      - "80:80" # Expose Nginx on port 80
      # - "443:443" # Uncomment if/when adding SSL
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d # Mount custom config
      # - ./nginx/ssl:/etc/nginx/ssl # Uncomment if/when adding SSL certs
    depends_on:
      - backend
      - frontend # Depends on original frontend
    networks:
      - default
      - supabase_network

# Define the networks
networks:
  default:
    driver: bridge
  supabase_network:
    external: true
    name: supabase_default # Corrected network name based on docker network ls

# Note: This basic setup doesn't include Supabase yet.
# Supabase would be added as another service. 