version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ghostly_backend
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/app:/app/app # Mount app code for hot-reloading
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1 # Ensures Python logs appear without delay

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ghostly_frontend
    # Use Vite dev server for development with hot-reload
    # The command overrides the CMD in the frontend Dockerfile (which uses nginx)
    command: npm run dev -- --host 0.0.0.0 --port 5173
    volumes:
      - ./frontend/src:/app/src # Mount src for hot-reloading
      - ./frontend/public:/app/public # Mount public assets
      - /app/node_modules # Use node_modules from image, don't mount local ones
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=development

# Note: This basic setup doesn't include Supabase or Nginx yet.
# Those would be added in later stages or via override files for production. 